# Base image
FROM python:3.9

# Set working directory
WORKDIR /semantic

# Copy requirements.txt file to container
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy semanticfiles to container
COPY . .

# Expose port 8080
EXPOSE 8080

# Run the semantic when the container starts
CMD ["python", "semantic.py"]
